/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	zalandoorgv1 "github.com/zalando-incubator/kube-metrics-adapter/pkg/apis/zalando.org/v1"
	internal "github.com/zalando-incubator/kube-metrics-adapter/pkg/client/applyconfiguration/internal"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	managedfields "k8s.io/apimachinery/pkg/util/managedfields"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ClusterScalingScheduleApplyConfiguration represents a declarative configuration of the ClusterScalingSchedule type for use
// with apply.
//
// ClusterScalingSchedule describes a cluster scoped time based metric
// to be used in autoscaling operations.
type ClusterScalingScheduleApplyConfiguration struct {
	metav1.TypeMetaApplyConfiguration    `json:",inline"`
	*metav1.ObjectMetaApplyConfiguration `json:"metadata,omitempty"`
	Spec                                 *ScalingScheduleSpecApplyConfiguration   `json:"spec,omitempty"`
	Status                               *ScalingScheduleStatusApplyConfiguration `json:"status,omitempty"`
}

// ClusterScalingSchedule constructs a declarative configuration of the ClusterScalingSchedule type for use with
// apply.
func ClusterScalingSchedule(name string) *ClusterScalingScheduleApplyConfiguration {
	b := &ClusterScalingScheduleApplyConfiguration{}
	b.WithName(name)
	b.WithKind("ClusterScalingSchedule")
	b.WithAPIVersion("zalando.org/v1")
	return b
}

// ExtractClusterScalingScheduleFrom extracts the applied configuration owned by fieldManager from
// clusterScalingSchedule for the specified subresource. Pass an empty string for subresource to extract
// the main resource. Common subresources include "status", "scale", etc.
// clusterScalingSchedule must be a unmodified ClusterScalingSchedule API object that was retrieved from the Kubernetes API.
// ExtractClusterScalingScheduleFrom provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractClusterScalingScheduleFrom(clusterScalingSchedule *zalandoorgv1.ClusterScalingSchedule, fieldManager string, subresource string) (*ClusterScalingScheduleApplyConfiguration, error) {
	b := &ClusterScalingScheduleApplyConfiguration{}
	err := managedfields.ExtractInto(clusterScalingSchedule, internal.Parser().Type("com.github.zalando-incubator.kube-metrics-adapter.pkg.apis.zalando.org.v1.ClusterScalingSchedule"), fieldManager, b, subresource)
	if err != nil {
		return nil, err
	}
	b.WithName(clusterScalingSchedule.Name)

	b.WithKind("ClusterScalingSchedule")
	b.WithAPIVersion("zalando.org/v1")
	return b, nil
}

// ExtractClusterScalingSchedule extracts the applied configuration owned by fieldManager from
// clusterScalingSchedule. If no managedFields are found in clusterScalingSchedule for fieldManager, a
// ClusterScalingScheduleApplyConfiguration is returned with only the Name, Namespace (if applicable),
// APIVersion and Kind populated. It is possible that no managed fields were found for because other
// field managers have taken ownership of all the fields previously owned by fieldManager, or because
// the fieldManager never owned fields any fields.
// clusterScalingSchedule must be a unmodified ClusterScalingSchedule API object that was retrieved from the Kubernetes API.
// ExtractClusterScalingSchedule provides a way to perform a extract/modify-in-place/apply workflow.
// Note that an extracted apply configuration will contain fewer fields than what the fieldManager previously
// applied if another fieldManager has updated or force applied any of the previously applied fields.
func ExtractClusterScalingSchedule(clusterScalingSchedule *zalandoorgv1.ClusterScalingSchedule, fieldManager string) (*ClusterScalingScheduleApplyConfiguration, error) {
	return ExtractClusterScalingScheduleFrom(clusterScalingSchedule, fieldManager, "")
}

// ExtractClusterScalingScheduleStatus extracts the applied configuration owned by fieldManager from
// clusterScalingSchedule for the status subresource.
func ExtractClusterScalingScheduleStatus(clusterScalingSchedule *zalandoorgv1.ClusterScalingSchedule, fieldManager string) (*ClusterScalingScheduleApplyConfiguration, error) {
	return ExtractClusterScalingScheduleFrom(clusterScalingSchedule, fieldManager, "status")
}

func (b ClusterScalingScheduleApplyConfiguration) IsApplyConfiguration() {}

// WithKind sets the Kind field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Kind field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithKind(value string) *ClusterScalingScheduleApplyConfiguration {
	b.TypeMetaApplyConfiguration.Kind = &value
	return b
}

// WithAPIVersion sets the APIVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the APIVersion field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithAPIVersion(value string) *ClusterScalingScheduleApplyConfiguration {
	b.TypeMetaApplyConfiguration.APIVersion = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithName(value string) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Name = &value
	return b
}

// WithGenerateName sets the GenerateName field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GenerateName field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithGenerateName(value string) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.GenerateName = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithNamespace(value string) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Namespace = &value
	return b
}

// WithUID sets the UID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UID field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithUID(value types.UID) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.UID = &value
	return b
}

// WithResourceVersion sets the ResourceVersion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ResourceVersion field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithResourceVersion(value string) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.ResourceVersion = &value
	return b
}

// WithGeneration sets the Generation field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Generation field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithGeneration(value int64) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.Generation = &value
	return b
}

// WithCreationTimestamp sets the CreationTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreationTimestamp field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithCreationTimestamp(value apismetav1.Time) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.CreationTimestamp = &value
	return b
}

// WithDeletionTimestamp sets the DeletionTimestamp field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionTimestamp field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithDeletionTimestamp(value apismetav1.Time) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionTimestamp = &value
	return b
}

// WithDeletionGracePeriodSeconds sets the DeletionGracePeriodSeconds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeletionGracePeriodSeconds field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithDeletionGracePeriodSeconds(value int64) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	b.ObjectMetaApplyConfiguration.DeletionGracePeriodSeconds = &value
	return b
}

// WithLabels puts the entries into the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Labels field,
// overwriting an existing map entries in Labels field with the same key.
func (b *ClusterScalingScheduleApplyConfiguration) WithLabels(entries map[string]string) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Labels == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Labels = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Labels[k] = v
	}
	return b
}

// WithAnnotations puts the entries into the Annotations field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, the entries provided by each call will be put on the Annotations field,
// overwriting an existing map entries in Annotations field with the same key.
func (b *ClusterScalingScheduleApplyConfiguration) WithAnnotations(entries map[string]string) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	if b.ObjectMetaApplyConfiguration.Annotations == nil && len(entries) > 0 {
		b.ObjectMetaApplyConfiguration.Annotations = make(map[string]string, len(entries))
	}
	for k, v := range entries {
		b.ObjectMetaApplyConfiguration.Annotations[k] = v
	}
	return b
}

// WithOwnerReferences adds the given value to the OwnerReferences field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the OwnerReferences field.
func (b *ClusterScalingScheduleApplyConfiguration) WithOwnerReferences(values ...*metav1.OwnerReferenceApplyConfiguration) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithOwnerReferences")
		}
		b.ObjectMetaApplyConfiguration.OwnerReferences = append(b.ObjectMetaApplyConfiguration.OwnerReferences, *values[i])
	}
	return b
}

// WithFinalizers adds the given value to the Finalizers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Finalizers field.
func (b *ClusterScalingScheduleApplyConfiguration) WithFinalizers(values ...string) *ClusterScalingScheduleApplyConfiguration {
	b.ensureObjectMetaApplyConfigurationExists()
	for i := range values {
		b.ObjectMetaApplyConfiguration.Finalizers = append(b.ObjectMetaApplyConfiguration.Finalizers, values[i])
	}
	return b
}

func (b *ClusterScalingScheduleApplyConfiguration) ensureObjectMetaApplyConfigurationExists() {
	if b.ObjectMetaApplyConfiguration == nil {
		b.ObjectMetaApplyConfiguration = &metav1.ObjectMetaApplyConfiguration{}
	}
}

// WithSpec sets the Spec field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Spec field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithSpec(value *ScalingScheduleSpecApplyConfiguration) *ClusterScalingScheduleApplyConfiguration {
	b.Spec = value
	return b
}

// WithStatus sets the Status field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Status field is set to the value of the last call.
func (b *ClusterScalingScheduleApplyConfiguration) WithStatus(value *ScalingScheduleStatusApplyConfiguration) *ClusterScalingScheduleApplyConfiguration {
	b.Status = value
	return b
}

// GetKind retrieves the value of the Kind field in the declarative configuration.
func (b *ClusterScalingScheduleApplyConfiguration) GetKind() *string {
	return b.TypeMetaApplyConfiguration.Kind
}

// GetAPIVersion retrieves the value of the APIVersion field in the declarative configuration.
func (b *ClusterScalingScheduleApplyConfiguration) GetAPIVersion() *string {
	return b.TypeMetaApplyConfiguration.APIVersion
}

// GetName retrieves the value of the Name field in the declarative configuration.
func (b *ClusterScalingScheduleApplyConfiguration) GetName() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Name
}

// GetNamespace retrieves the value of the Namespace field in the declarative configuration.
func (b *ClusterScalingScheduleApplyConfiguration) GetNamespace() *string {
	b.ensureObjectMetaApplyConfigurationExists()
	return b.ObjectMetaApplyConfiguration.Namespace
}
