/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ScalingScheduleSpecApplyConfiguration represents a declarative configuration of the ScalingScheduleSpec type for use
// with apply.
//
// ScalingScheduleSpec is the spec part of the ScalingSchedule.
type ScalingScheduleSpecApplyConfiguration struct {
	// Fade the scheduled values in and out over this many minutes. If unset, the default per-cluster value will be used.
	ScalingWindowDurationMinutes *int64 `json:"scalingWindowDurationMinutes,omitempty"`
	// Schedules is the list of schedules for this ScalingSchedule
	// resource. All the schedules defined here will result on the value
	// to the same metric. New metrics require a new ScalingSchedule
	// resource.
	Schedules []ScheduleApplyConfiguration `json:"schedules,omitempty"`
}

// ScalingScheduleSpecApplyConfiguration constructs a declarative configuration of the ScalingScheduleSpec type for use with
// apply.
func ScalingScheduleSpec() *ScalingScheduleSpecApplyConfiguration {
	return &ScalingScheduleSpecApplyConfiguration{}
}

// WithScalingWindowDurationMinutes sets the ScalingWindowDurationMinutes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ScalingWindowDurationMinutes field is set to the value of the last call.
func (b *ScalingScheduleSpecApplyConfiguration) WithScalingWindowDurationMinutes(value int64) *ScalingScheduleSpecApplyConfiguration {
	b.ScalingWindowDurationMinutes = &value
	return b
}

// WithSchedules adds the given value to the Schedules field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Schedules field.
func (b *ScalingScheduleSpecApplyConfiguration) WithSchedules(values ...*ScheduleApplyConfiguration) *ScalingScheduleSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSchedules")
		}
		b.Schedules = append(b.Schedules, *values[i])
	}
	return b
}
