/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

// ScalingScheduleStatusApplyConfiguration represents a declarative configuration of the ScalingScheduleStatus type for use
// with apply.
//
// ScalingScheduleStatus is the status section of the ScalingSchedule.
type ScalingScheduleStatusApplyConfiguration struct {
	// Active is true if at least one of the schedules defined in the
	// scaling schedule is currently active.
	Active *bool `json:"active,omitempty"`
}

// ScalingScheduleStatusApplyConfiguration constructs a declarative configuration of the ScalingScheduleStatus type for use with
// apply.
func ScalingScheduleStatus() *ScalingScheduleStatusApplyConfiguration {
	return &ScalingScheduleStatusApplyConfiguration{}
}

// WithActive sets the Active field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Active field is set to the value of the last call.
func (b *ScalingScheduleStatusApplyConfiguration) WithActive(value bool) *ScalingScheduleStatusApplyConfiguration {
	b.Active = &value
	return b
}
