/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	zalandoorgv1 "github.com/zalando-incubator/kube-metrics-adapter/pkg/apis/zalando.org/v1"
)

// SchedulePeriodApplyConfiguration represents a declarative configuration of the SchedulePeriod type for use
// with apply.
//
// SchedulePeriod is the details to be used for a Schedule of the
// Repeating type.
type SchedulePeriodApplyConfiguration struct {
	// The startTime has the format HH:MM
	StartTime *string `json:"startTime,omitempty"`
	// The endTime has the format HH:MM
	EndTime *string `json:"endTime,omitempty"`
	// The days that this schedule will be active.
	Days []zalandoorgv1.ScheduleDay `json:"days,omitempty"`
	// The location name corresponding to a file in the IANA
	// Time Zone database, like Europe/Berlin.
	Timezone *string `json:"timezone,omitempty"`
}

// SchedulePeriodApplyConfiguration constructs a declarative configuration of the SchedulePeriod type for use with
// apply.
func SchedulePeriod() *SchedulePeriodApplyConfiguration {
	return &SchedulePeriodApplyConfiguration{}
}

// WithStartTime sets the StartTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the StartTime field is set to the value of the last call.
func (b *SchedulePeriodApplyConfiguration) WithStartTime(value string) *SchedulePeriodApplyConfiguration {
	b.StartTime = &value
	return b
}

// WithEndTime sets the EndTime field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndTime field is set to the value of the last call.
func (b *SchedulePeriodApplyConfiguration) WithEndTime(value string) *SchedulePeriodApplyConfiguration {
	b.EndTime = &value
	return b
}

// WithDays adds the given value to the Days field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Days field.
func (b *SchedulePeriodApplyConfiguration) WithDays(values ...zalandoorgv1.ScheduleDay) *SchedulePeriodApplyConfiguration {
	for i := range values {
		b.Days = append(b.Days, values[i])
	}
	return b
}

// WithTimezone sets the Timezone field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Timezone field is set to the value of the last call.
func (b *SchedulePeriodApplyConfiguration) WithTimezone(value string) *SchedulePeriodApplyConfiguration {
	b.Timezone = &value
	return b
}
