/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1

import (
	zalandoorgv1 "github.com/zalando-incubator/kube-metrics-adapter/pkg/apis/zalando.org/v1"
)

// ScheduleApplyConfiguration represents a declarative configuration of the Schedule type for use
// with apply.
//
// Schedule is the schedule details to be used inside a ScalingSchedule.
type ScheduleApplyConfiguration struct {
	Type *zalandoorgv1.ScheduleType `json:"type,omitempty"`
	// Defines the details of a Repeating schedule.
	Period *SchedulePeriodApplyConfiguration `json:"period,omitempty"`
	// Defines the starting date of a OneTime schedule. It has to
	// be a RFC3339 formatted date.
	Date *zalandoorgv1.ScheduleDate `json:"date,omitempty"`
	// Defines the ending date of a OneTime schedule. It must be
	// a RFC3339 formatted date.
	EndDate *zalandoorgv1.ScheduleDate `json:"endDate,omitempty"`
	// The duration in minutes (default 0) that the configured value will be
	// returned for the defined schedule.
	DurationMinutes *int `json:"durationMinutes,omitempty"`
	// The metric value that will be returned for the defined schedule.
	Value *int64 `json:"value,omitempty"`
}

// ScheduleApplyConfiguration constructs a declarative configuration of the Schedule type for use with
// apply.
func Schedule() *ScheduleApplyConfiguration {
	return &ScheduleApplyConfiguration{}
}

// WithType sets the Type field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Type field is set to the value of the last call.
func (b *ScheduleApplyConfiguration) WithType(value zalandoorgv1.ScheduleType) *ScheduleApplyConfiguration {
	b.Type = &value
	return b
}

// WithPeriod sets the Period field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Period field is set to the value of the last call.
func (b *ScheduleApplyConfiguration) WithPeriod(value *SchedulePeriodApplyConfiguration) *ScheduleApplyConfiguration {
	b.Period = value
	return b
}

// WithDate sets the Date field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Date field is set to the value of the last call.
func (b *ScheduleApplyConfiguration) WithDate(value zalandoorgv1.ScheduleDate) *ScheduleApplyConfiguration {
	b.Date = &value
	return b
}

// WithEndDate sets the EndDate field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EndDate field is set to the value of the last call.
func (b *ScheduleApplyConfiguration) WithEndDate(value zalandoorgv1.ScheduleDate) *ScheduleApplyConfiguration {
	b.EndDate = &value
	return b
}

// WithDurationMinutes sets the DurationMinutes field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DurationMinutes field is set to the value of the last call.
func (b *ScheduleApplyConfiguration) WithDurationMinutes(value int) *ScheduleApplyConfiguration {
	b.DurationMinutes = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *ScheduleApplyConfiguration) WithValue(value int64) *ScheduleApplyConfiguration {
	b.Value = &value
	return b
}
